default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: mini_blog_development
  port: 5432

test:
  <<: *default
  database: mini_blog_test

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  primary: &primary_production
    <<: *default
    database: mini_blog_production
    username: mini_blog
    password: <%= ENV["MINI_BLOG_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: mini_blog_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: mini_blog_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: mini_blog_production_cable
    migrations_paths: db/cable_migrate
